# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Nick's Blog
tagline:          What goes on in my head
url:              #
paginate:         1
baseurl:          /
author:
  name:           Nick Hurford
  url:            https://twitter.com/nick_hurford
  email:          nick@pinegreen.co.uk

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
